// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eComSolution.Data.EF;

namespace eComSolution.Data.Migrations
{
    [DbContext(typeof(EComDbContext))]
    [Migration("20211104081014_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eComSolution.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetail_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 150000,
                            ProductDetail_Id = 8,
                            Quantity = 10,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Áo Thun",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Áo Sơ mi",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Áo Hoodie",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quần Jean",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Đồ lót",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Váy",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Đầm",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Accounts.Register"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Accounts.Login"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mod"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.GroupUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            UserId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 1,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 2,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 4,
                            GroupId = 3
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Histories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Date = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(8423),
                            ProductId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            Date = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(9006),
                            ProductId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            Date = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(9011),
                            ProductId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateModified = new DateTime(2021, 11, 4, 15, 10, 13, 711, DateTimeKind.Local).AddTicks(1884),
                            OrderDate = new DateTime(2021, 11, 4, 15, 10, 13, 711, DateTimeKind.Local).AddTicks(1500),
                            ShipAddress = "123 Lê Duẩn, Thanh Khê, Đà Nẵng",
                            ShipName = "Đinh Công Tài",
                            ShipPhone = "09053438847",
                            ShopId = 2,
                            State = "Chờ xử lý",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetail_Id");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 250000,
                            ProductDetail_Id = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 250000,
                            ProductDetail_Id = 13,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Permission", b =>
                {
                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("FunctionId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            FunctionId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 1
                        },
                        new
                        {
                            FunctionId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            FunctionId = 1,
                            GroupId = 3
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 3
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(3429),
                            Description = "Mô tả sản phẩm:\n Chất liệu: 100% cotton\n Màu sắc : trắng & đen",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Áo thun SadBoiz",
                            OriginalPrice = 100000,
                            Price = 200000,
                            ShopId = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(5312),
                            Description = "Mô tả sản phẩm:\n Chất liệu: 100% cotton\n Màu sắc : đỏ & đen",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Quần lót Calvin Klein",
                            OriginalPrice = 100000,
                            Price = 150000,
                            ShopId = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(5320),
                            Description = "Mô tả sản phẩm:\n Brand: XFire\n Chất liệu : cotton co dãn",
                            Gender = 3,
                            IsDeleted = false,
                            Name = "Áo thun trơn XFire",
                            OriginalPrice = 150000,
                            Price = 250000,
                            ShopId = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 710, DateTimeKind.Local).AddTicks(5322),
                            Description = "Mô tả sản phẩm:\n Form: Fit\n Chất liệu : jean",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Quần Jean ôm nam",
                            OriginalPrice = 150000,
                            Price = 250000,
                            ShopId = 2,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Color = "Trắng",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Color = "Trắng",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "M",
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "M",
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 10,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 11,
                            Color = "Xám",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            Color = "Xám",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 13,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 4,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 4,
                            Size = "L",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSizeDetail")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ResetPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numcheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResetPasses");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 DT605, Hòa Tiến, Hòa Vang, Đà Nẵng",
                            Avatar = "",
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 704, DateTimeKind.Local).AddTicks(5936),
                            DateModified = new DateTime(2021, 11, 4, 15, 10, 13, 705, DateTimeKind.Local).AddTicks(5635),
                            Description = "Cửa hàng áo quần chất lượng cao, giá cả phải chăng",
                            Disable = false,
                            Name = "Tuấn's Fashion",
                            PhoneNumber = "0921231220"
                        },
                        new
                        {
                            Id = 2,
                            Address = "160 Trần Nhật Duật, Cẩm Châu, Hội An, Quảng Nam",
                            Avatar = "",
                            DateCreated = new DateTime(2021, 11, 4, 15, 10, 13, 705, DateTimeKind.Local).AddTicks(6396),
                            DateModified = new DateTime(2021, 11, 4, 15, 10, 13, 705, DateTimeKind.Local).AddTicks(6402),
                            Description = "Cửa hàng áo quần nam",
                            Disable = false,
                            Name = "Đạt's Clothes",
                            PhoneNumber = "0905553859"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(62)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(62)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique()
                        .HasFilter("[ShopId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disable = false,
                            Email = "tuandang29042000@gmail.com",
                            Fullname = "admin",
                            PasswordHash = new byte[] { 126, 208, 99, 57, 66, 169, 170, 241, 7, 93, 187, 165, 142, 88, 104, 27, 229, 39, 13, 165, 135, 29, 70, 90, 1, 60, 19, 146, 167, 249, 198, 66, 92, 172, 209, 200, 33, 212, 146, 38, 53, 196, 150, 96, 89, 67, 213, 102, 190, 217, 42, 190, 118, 14, 221, 208, 2, 110, 135, 157, 231, 163, 248, 42 },
                            PasswordSalt = new byte[] { 249, 45, 232, 251, 29, 246, 235, 13, 23, 88, 254, 193, 249, 127, 88, 249, 36, 255, 234, 35, 78, 124, 210, 73, 15, 89, 34, 101, 249, 52, 50, 12, 131, 252, 78, 53, 152, 225, 124, 24, 91, 127, 78, 194, 71, 100, 43, 92, 181, 89, 93, 18, 129, 200, 50, 246, 254, 106, 134, 117, 155, 94, 144, 169, 35, 245, 213, 100, 55, 65, 42, 126, 109, 90, 122, 7, 255, 63, 53, 134, 77, 106, 80, 147, 203, 11, 13, 131, 232, 172, 203, 137, 18, 56, 188, 58, 92, 248, 124, 71, 182, 181, 17, 36, 11, 177, 189, 108, 61, 209, 212, 38, 223, 244, 48, 166, 90, 244, 98, 30, 186, 180, 85, 37, 175, 200, 100, 75 },
                            PhoneNumber = "0921231220",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 DT605, Hòa Tiến, Hòa Vang, Đà Nẵng",
                            Disable = false,
                            Email = "tuandang29042000@gmail.com",
                            Fullname = "Đặng Quốc Tuấn",
                            PasswordHash = new byte[] { 158, 231, 143, 223, 29, 20, 180, 98, 78, 129, 63, 67, 17, 204, 90, 62, 85, 236, 110, 161, 148, 151, 121, 108, 201, 196, 234, 116, 78, 229, 204, 104, 115, 33, 113, 153, 119, 34, 244, 68, 140, 206, 241, 58, 69, 44, 164, 41, 127, 26, 165, 161, 117, 175, 147, 199, 110, 36, 106, 237, 217, 13, 105, 184 },
                            PasswordSalt = new byte[] { 249, 45, 232, 251, 29, 246, 235, 13, 23, 88, 254, 193, 249, 127, 88, 249, 36, 255, 234, 35, 78, 124, 210, 73, 15, 89, 34, 101, 249, 52, 50, 12, 131, 252, 78, 53, 152, 225, 124, 24, 91, 127, 78, 194, 71, 100, 43, 92, 181, 89, 93, 18, 129, 200, 50, 246, 254, 106, 134, 117, 155, 94, 144, 169, 35, 245, 213, 100, 55, 65, 42, 126, 109, 90, 122, 7, 255, 63, 53, 134, 77, 106, 80, 147, 203, 11, 13, 131, 232, 172, 203, 137, 18, 56, 188, 58, 92, 248, 124, 71, 182, 181, 17, 36, 11, 177, 189, 108, 61, 209, 212, 38, 223, 244, 48, 166, 90, 244, 98, 30, 186, 180, 85, 37, 175, 200, 100, 75 },
                            PhoneNumber = "0921231220",
                            ShopId = 1,
                            Username = "quoctuan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "160 Trần Nhật Duật, Hội An, Quảng Nam",
                            Disable = false,
                            Email = "ngoluuquocdat@gmail.com",
                            Fullname = "Ngô Lưu Quốc Đạt",
                            PasswordHash = new byte[] { 88, 153, 80, 29, 204, 114, 112, 42, 206, 222, 90, 108, 170, 155, 105, 187, 214, 157, 81, 117, 44, 202, 173, 132, 105, 249, 62, 1, 186, 219, 155, 210, 82, 177, 223, 21, 122, 143, 47, 244, 224, 41, 244, 114, 60, 166, 196, 189, 143, 217, 81, 42, 31, 217, 230, 26, 121, 221, 149, 134, 249, 124, 244, 43 },
                            PasswordSalt = new byte[] { 249, 45, 232, 251, 29, 246, 235, 13, 23, 88, 254, 193, 249, 127, 88, 249, 36, 255, 234, 35, 78, 124, 210, 73, 15, 89, 34, 101, 249, 52, 50, 12, 131, 252, 78, 53, 152, 225, 124, 24, 91, 127, 78, 194, 71, 100, 43, 92, 181, 89, 93, 18, 129, 200, 50, 246, 254, 106, 134, 117, 155, 94, 144, 169, 35, 245, 213, 100, 55, 65, 42, 126, 109, 90, 122, 7, 255, 63, 53, 134, 77, 106, 80, 147, 203, 11, 13, 131, 232, 172, 203, 137, 18, 56, 188, 58, 92, 248, 124, 71, 182, 181, 17, 36, 11, 177, 189, 108, 61, 209, 212, 38, 223, 244, 48, 166, 90, 244, 98, 30, 186, 180, 85, 37, 175, 200, 100, 75 },
                            PhoneNumber = "090553859",
                            ShopId = 2,
                            Username = "quocdat"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Lê Duẩn, Thanh Khê, Đà Nẵng",
                            Disable = false,
                            Email = "badding@gmail.com",
                            Fullname = "Đinh Công Tài",
                            PasswordHash = new byte[] { 121, 134, 2, 14, 214, 150, 158, 119, 1, 205, 184, 43, 33, 189, 138, 85, 13, 103, 99, 15, 62, 234, 119, 81, 66, 109, 109, 130, 74, 215, 197, 240, 51, 168, 210, 208, 17, 25, 125, 128, 25, 255, 215, 18, 229, 48, 232, 110, 26, 163, 50, 205, 60, 11, 178, 237, 108, 161, 148, 33, 8, 63, 68, 208 },
                            PasswordSalt = new byte[] { 249, 45, 232, 251, 29, 246, 235, 13, 23, 88, 254, 193, 249, 127, 88, 249, 36, 255, 234, 35, 78, 124, 210, 73, 15, 89, 34, 101, 249, 52, 50, 12, 131, 252, 78, 53, 152, 225, 124, 24, 91, 127, 78, 194, 71, 100, 43, 92, 181, 89, 93, 18, 129, 200, 50, 246, 254, 106, 134, 117, 155, 94, 144, 169, 35, 245, 213, 100, 55, 65, 42, 126, 109, 90, 122, 7, 255, 63, 53, 134, 77, 106, 80, 147, 203, 11, 13, 131, 232, 172, 203, 137, 18, 56, 188, 58, 92, 248, 124, 71, 182, 181, 17, 36, 11, 177, 189, 108, 61, 209, 212, 38, 223, 244, 48, 166, 90, 244, 98, 30, 186, 180, 85, 37, 175, 200, 100, 75 },
                            PhoneNumber = "090553859",
                            Username = "congtai"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Cart", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.ProductDetail", "ProductDetail")
                        .WithMany("Carts")
                        .HasForeignKey("ProductDetail_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.GroupUser", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.History", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("Histories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithMany("Orders")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.ProductDetail", "ProductDetail")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductDetail_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Permission", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Function", "Function")
                        .WithMany("Permissions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.Group", "Group")
                        .WithMany("Permissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithOne("User")
                        .HasForeignKey("eComSolution.Data.Entities.User", "ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Function", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Group", b =>
                {
                    b.Navigation("GroupUsers");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Shop", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("GroupUsers");

                    b.Navigation("Histories");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
