// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eComSolution.Data.EF;

namespace eComSolution.Data.Migrations
{
    [DbContext(typeof(EComDbContext))]
    [Migration("20211110030252_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eComSolution.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductDetail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetail_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductDetail_Id = 8,
                            Quantity = 10,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Áo Thun",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Áo Sơ mi",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Áo Hoodie",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quần Jean",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Đồ lót",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Váy",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Đầm",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Accounts.Register"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Accounts.Login"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mod"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.GroupUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            UserId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 1,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 2,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 4,
                            GroupId = 3
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Histories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Date = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(7101),
                            ProductId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            Date = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(7558),
                            ProductId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            Date = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(7562),
                            ProductId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateModified = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(9896),
                            OrderDate = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(9642),
                            ShipAddress = "123 Lê Duẩn, Thanh Khê, Đà Nẵng",
                            ShipName = "Đinh Công Tài",
                            ShipPhone = "09053438847",
                            ShopId = 2,
                            State = "Chờ xử lý",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetail_Id");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 250000,
                            ProductDetail_Id = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 250000,
                            ProductDetail_Id = 13,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Permission", b =>
                {
                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("FunctionId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            FunctionId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 1
                        },
                        new
                        {
                            FunctionId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            FunctionId = 1,
                            GroupId = 3
                        },
                        new
                        {
                            FunctionId = 2,
                            GroupId = 3
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(3112),
                            Description = "Mô tả sản phẩm:\n Chất liệu: 100% cotton\n Màu sắc : trắng & đen",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Áo thun SadBoiz",
                            OriginalPrice = 100000,
                            Price = 200000,
                            ShopId = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(4602),
                            Description = "Mô tả sản phẩm:\n Chất liệu: 100% cotton\n Màu sắc : đỏ & đen",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Quần lót Calvin Klein",
                            OriginalPrice = 100000,
                            Price = 150000,
                            ShopId = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(4607),
                            Description = "Mô tả sản phẩm:\n Brand: XFire\n Chất liệu : cotton co dãn",
                            Gender = 3,
                            IsDeleted = false,
                            Name = "Áo thun trơn XFire",
                            OriginalPrice = 150000,
                            Price = 250000,
                            ShopId = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 817, DateTimeKind.Local).AddTicks(4609),
                            Description = "Mô tả sản phẩm:\n Form: Fit\n Chất liệu : jean",
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Quần Jean ôm nam",
                            OriginalPrice = 150000,
                            Price = 250000,
                            ShopId = 2,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Color = "Trắng",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Color = "Trắng",
                            IsDeleted = false,
                            ProductId = 1,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "M",
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 2,
                            Size = "M",
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 10,
                            Color = "Đỏ",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 11,
                            Color = "Xám",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            Color = "Xám",
                            IsDeleted = false,
                            ProductId = 3,
                            Size = "L",
                            Stock = 10
                        },
                        new
                        {
                            Id = 13,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 4,
                            Size = "XL",
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            Color = "Đen",
                            IsDeleted = false,
                            ProductId = 4,
                            Size = "L",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSizeDetail")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ResetPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numcheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResetPasses");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("DisableReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 DT605, Hòa Tiến, Hòa Vang, Đà Nẵng",
                            Avatar = "",
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 812, DateTimeKind.Local).AddTicks(8087),
                            DateModified = new DateTime(2021, 11, 10, 10, 2, 51, 813, DateTimeKind.Local).AddTicks(5408),
                            Description = "Cửa hàng áo quần chất lượng cao, giá cả phải chăng",
                            Disable = false,
                            Name = "Tuấn's Fashion",
                            PhoneNumber = "0921231220"
                        },
                        new
                        {
                            Id = 2,
                            Address = "160 Trần Nhật Duật, Cẩm Châu, Hội An, Quảng Nam",
                            Avatar = "",
                            DateCreated = new DateTime(2021, 11, 10, 10, 2, 51, 813, DateTimeKind.Local).AddTicks(6118),
                            DateModified = new DateTime(2021, 11, 10, 10, 2, 51, 813, DateTimeKind.Local).AddTicks(6122),
                            Description = "Cửa hàng áo quần nam",
                            Disable = false,
                            Name = "Đạt's Clothes",
                            PhoneNumber = "0905553859"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(62)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(62)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique()
                        .HasFilter("[ShopId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disable = false,
                            Email = "tuandang29042000@gmail.com",
                            Fullname = "admin",
                            PasswordHash = new byte[] { 121, 186, 32, 3, 50, 116, 233, 254, 3, 61, 56, 22, 58, 73, 141, 127, 60, 70, 128, 88, 143, 16, 20, 6, 201, 103, 73, 209, 200, 208, 110, 210, 229, 99, 39, 110, 186, 149, 245, 236, 152, 198, 159, 11, 73, 35, 115, 151, 101, 250, 45, 190, 232, 249, 72, 12, 115, 204, 181, 138, 138, 56, 216, 145 },
                            PasswordSalt = new byte[] { 180, 66, 173, 108, 108, 108, 103, 196, 143, 173, 157, 3, 230, 163, 86, 85, 150, 89, 115, 199, 84, 56, 182, 56, 59, 248, 226, 208, 145, 84, 207, 178, 230, 104, 3, 39, 241, 230, 227, 82, 80, 236, 132, 157, 198, 146, 246, 239, 185, 117, 87, 228, 43, 228, 223, 181, 140, 111, 110, 217, 169, 231, 127, 178, 50, 255, 86, 189, 120, 41, 64, 173, 48, 60, 182, 245, 115, 143, 39, 101, 199, 5, 54, 230, 243, 97, 142, 252, 47, 30, 20, 82, 27, 93, 193, 16, 65, 45, 183, 75, 215, 97, 100, 111, 119, 125, 233, 123, 132, 51, 191, 112, 8, 207, 208, 30, 32, 85, 133, 210, 115, 141, 169, 97, 143, 87, 213, 8 },
                            PhoneNumber = "0921231220",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 DT605, Hòa Tiến, Hòa Vang, Đà Nẵng",
                            Disable = false,
                            Email = "tuandang29042000@gmail.com",
                            Fullname = "Đặng Quốc Tuấn",
                            PasswordHash = new byte[] { 4, 150, 156, 46, 123, 214, 191, 29, 222, 48, 140, 244, 52, 206, 105, 89, 46, 36, 113, 239, 252, 104, 39, 148, 3, 90, 120, 162, 30, 201, 109, 234, 244, 140, 40, 47, 232, 36, 43, 83, 104, 181, 125, 198, 247, 22, 251, 74, 139, 91, 157, 249, 165, 100, 56, 139, 97, 81, 173, 110, 250, 196, 95, 185 },
                            PasswordSalt = new byte[] { 180, 66, 173, 108, 108, 108, 103, 196, 143, 173, 157, 3, 230, 163, 86, 85, 150, 89, 115, 199, 84, 56, 182, 56, 59, 248, 226, 208, 145, 84, 207, 178, 230, 104, 3, 39, 241, 230, 227, 82, 80, 236, 132, 157, 198, 146, 246, 239, 185, 117, 87, 228, 43, 228, 223, 181, 140, 111, 110, 217, 169, 231, 127, 178, 50, 255, 86, 189, 120, 41, 64, 173, 48, 60, 182, 245, 115, 143, 39, 101, 199, 5, 54, 230, 243, 97, 142, 252, 47, 30, 20, 82, 27, 93, 193, 16, 65, 45, 183, 75, 215, 97, 100, 111, 119, 125, 233, 123, 132, 51, 191, 112, 8, 207, 208, 30, 32, 85, 133, 210, 115, 141, 169, 97, 143, 87, 213, 8 },
                            PhoneNumber = "0921231220",
                            ShopId = 1,
                            Username = "quoctuan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "160 Trần Nhật Duật, Hội An, Quảng Nam",
                            Disable = false,
                            Email = "ngoluuquocdat@gmail.com",
                            Fullname = "Ngô Lưu Quốc Đạt",
                            PasswordHash = new byte[] { 135, 116, 199, 203, 97, 178, 52, 219, 250, 139, 22, 56, 196, 191, 110, 29, 90, 168, 159, 185, 71, 64, 137, 139, 199, 72, 132, 230, 101, 1, 195, 235, 156, 111, 16, 60, 13, 1, 110, 86, 49, 235, 78, 124, 239, 74, 139, 18, 222, 11, 209, 15, 92, 97, 2, 134, 20, 34, 222, 237, 234, 183, 134, 223 },
                            PasswordSalt = new byte[] { 180, 66, 173, 108, 108, 108, 103, 196, 143, 173, 157, 3, 230, 163, 86, 85, 150, 89, 115, 199, 84, 56, 182, 56, 59, 248, 226, 208, 145, 84, 207, 178, 230, 104, 3, 39, 241, 230, 227, 82, 80, 236, 132, 157, 198, 146, 246, 239, 185, 117, 87, 228, 43, 228, 223, 181, 140, 111, 110, 217, 169, 231, 127, 178, 50, 255, 86, 189, 120, 41, 64, 173, 48, 60, 182, 245, 115, 143, 39, 101, 199, 5, 54, 230, 243, 97, 142, 252, 47, 30, 20, 82, 27, 93, 193, 16, 65, 45, 183, 75, 215, 97, 100, 111, 119, 125, 233, 123, 132, 51, 191, 112, 8, 207, 208, 30, 32, 85, 133, 210, 115, 141, 169, 97, 143, 87, 213, 8 },
                            PhoneNumber = "090553859",
                            ShopId = 2,
                            Username = "quocdat"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Lê Duẩn, Thanh Khê, Đà Nẵng",
                            Disable = false,
                            Email = "badding@gmail.com",
                            Fullname = "Đinh Công Tài",
                            PasswordHash = new byte[] { 97, 75, 167, 213, 241, 173, 89, 32, 168, 199, 146, 143, 110, 85, 145, 182, 220, 160, 16, 151, 23, 248, 206, 236, 152, 58, 223, 231, 20, 167, 22, 136, 214, 64, 228, 212, 72, 81, 156, 162, 125, 184, 93, 85, 7, 102, 19, 233, 154, 220, 245, 14, 122, 85, 46, 148, 182, 235, 209, 96, 189, 235, 56, 44 },
                            PasswordSalt = new byte[] { 180, 66, 173, 108, 108, 108, 103, 196, 143, 173, 157, 3, 230, 163, 86, 85, 150, 89, 115, 199, 84, 56, 182, 56, 59, 248, 226, 208, 145, 84, 207, 178, 230, 104, 3, 39, 241, 230, 227, 82, 80, 236, 132, 157, 198, 146, 246, 239, 185, 117, 87, 228, 43, 228, 223, 181, 140, 111, 110, 217, 169, 231, 127, 178, 50, 255, 86, 189, 120, 41, 64, 173, 48, 60, 182, 245, 115, 143, 39, 101, 199, 5, 54, 230, 243, 97, 142, 252, 47, 30, 20, 82, 27, 93, 193, 16, 65, 45, 183, 75, 215, 97, 100, 111, 119, 125, 233, 123, 132, 51, 191, 112, 8, 207, 208, 30, 32, 85, 133, 210, 115, 141, 169, 97, 143, 87, 213, 8 },
                            PhoneNumber = "090553859",
                            Username = "congtai"
                        });
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Cart", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.ProductDetail", "ProductDetail")
                        .WithMany("Carts")
                        .HasForeignKey("ProductDetail_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.GroupUser", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.History", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("Histories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithMany("Orders")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.ProductDetail", "ProductDetail")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductDetail_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Permission", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Function", "Function")
                        .WithMany("Permissions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.Group", "Group")
                        .WithMany("Permissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.HasOne("eComSolution.Data.Entities.Shop", "Shop")
                        .WithOne("User")
                        .HasForeignKey("eComSolution.Data.Entities.User", "ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Function", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Group", b =>
                {
                    b.Navigation("GroupUsers");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Product", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.ProductDetail", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.Shop", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eComSolution.Data.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("GroupUsers");

                    b.Navigation("Histories");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
